### PR TITLE
0022   profile screen (slicing)

### PR DESCRIPTION
**Pull request by YahyaAiman**
Adding Profile Screen (slicing)
slice profil

### CODE REVIEW

**Review by FTioo — APPROVED** [review]

**Review by fernandjerico — APPROVED** [review]
kerenn mantapp

**Review by sycipss — APPROVED** [review]
Udah oke, tp mungkin biar ga overflow notenya nanti pake listview aja kali ya

**Comment by RizkyFaisalRafi** [comment]
Nice

**Review by RizkyFaisalRafi — APPROVED** [review]
Nice

**Pull request merged**
